### ISSUE TITLE
Adicio issues

### ISSUE THREAD

**Issue by psullivan6** [registerguard/drone#11]
I wanted to document the issues with Adicio, so just doing that here as I test.

**1.** Adicio automatically closes open `<div>`s that span from the header template to the footer template. **_Ex:**_

**THIS:**

``` html
<!-- ////////// [START] header \\\\\\\\\\ -->
<div class="foo">

    <div class="bar">
<!-- \\\\\\\\\\ [END] header //////////  -->

        <!-- ADICIO CONTENT HERE -->

<!-- ////////// [START] footer \\\\\\\\\\ -->
        <div class="baz">

            <p>stuff here</p>

        </div> <!-- /.baz -->

    </div> <!-- /.bar -->

</div> <!-- /.foo -->
<!-- \\\\\\\\\\ [END] footer //////////  -->

```

**DISPLAYS AS THIS:**

``` html
<div class="foo">

    <div class="bar">

        <!-- ADICIO CONTENT HERE -->

    </div> <!-- /.bar --> <!-- ########## CRAP CODE ########## -->

        <div class="baz">

            <p>stuff here</p>

        </div> <!-- /.baz -->

    </div> <!-- /.bar -->

</div> <!-- /.foo -->
```

---

...more to come

**Comment by mhulse** [comment]
I've never used this option myself ... I assume that you're not either ... Just thought I'd ask:

![screen shot 2013-08-05 at 2 44 28 pm](https://f.cloud.github.com/assets/218624/913477/05e49e3a-fe19-11e2-951c-e5ba14b29de1.png)

I wouldn't touch that setting with a 10 foot pole.

That's lame that they eff with your templates. Not sure why I never noticed myself.

**Comment by psullivan6** [comment]
> I've never used this option myself ...

I don't use that one either and probably won't :smile: 

---

**2.** The stylesheet via the **Styles** block is inserted directly into the `<head>` as a `<style>` tag **_after**_ the `<link>` tags declared in the **Head**block, thus the external sheets are overridden by this **Styles** block

**Solution:**
Include the base styles as a `<link>` instead? Sift through and remove styles that will override theme-based ones from raptor or adicio?

**Comment by psullivan6** [comment]
I've isolated **1** to just "Bargain Basket" listings. Something about these listings must be causing the final `<div>` to close improperly. Will investigate with Jeff, Tyler, and Joe and report back.

**Comment by mhulse** [comment]
> I've isolated **1** to just "Bargain Basket" listings. Something about these listings must be causing the final `<div>` to close improperly. Will investigate with Jeff, Tyler, and Joe and report back.

I remember now. I did have similar problems (bad Adicio markup).

Check out my old template:

http://homes.registerguard.com/template/20130320/template.html

View source, and you'll see this:

``` html
<table>
    <tr>
        <td>
            <!-- Note: The table is only for Adicio hosted templates. -->
        </td>
    </tr>
</table>
```

The HTML comment is where the Adicio content goes.

It's a funky patch, but it works. Also, the bad markup is an Adico problem, and they don't seem to care (at least when I contacted them about it).

Here's the e-mail conversation I had with Sandra from 2010:

> Thanks!
> 
> It looks better now. Thanks for the patch.
> 
> Yah, it was kinda a headache to track down the rouge html elements...
> Hopefully I save someone on your end some time.
> 
> Thanks!
> 
> M
> 
> On Thu, Jun 10, 2010 at 4:03 PM, Sandra B wrote:
> 
> > Hi Micky,
> > 
> > I've seen this problem on that page before.  I wrapped our content in a
> > table and that seems to have fixed it. Let me know if the page looks ok now.
> > I will definitely take your comments and submit a defect and see if they can
> > fix it the right way.  I would not anticipate that it would be addressed by
> > your launch though.
> > 
> > Sandra
> > 
> > -----Original Message-----
> > From: Micky Hulse
> > Sent: Thursday, June 10, 2010 3:14 PM
> > To: Sandra B
> > Cc: Jeff A
> > Subject: Adicio HTML
> > 
> > Hi Sandra! Thanks again for all your help the other day. We are loving the
> > template manager. :)
> > 
> > Quick observation:
> > 
> > When viewing this page...
> > 
> > http://registeredguard.re.adicio.com/properties/ads/mediaKit.php
> > 
> > ... on my Mac/latest version of Firefox, the template is breaking
> > (mostly) towards the footer.
> > 
> > I copied the source code and put it on a server for me to edit/fix...
> > When I removed all of the Adicio HTML, the template looked fine. Long story
> > short, I narrowed down the problem to invalid markup in the Adicio HTML.
> > 
> > See this page:
> > 
> > http://assets.registerguard.com/demos/adicio/
> > 
> > If you view source, I have marked the invalid pieces with HTML comments. For
> > example:
> > 
> > &lt;!--
> > ########################
> > 
> > &lt;/div>
> > 
> > ########################
> > --&gt;
> > 
> > Is there any way I can fix your HTML? If not, could you pass this
> > information along to your dev folks? I don't think I can fix it with CSS
> > overrides... It is the type of thing that should be removed from the source
> > code. :)
> > 
> > Thanks!
> > Micky

**Comment by psullivan6** [comment]
Closing this, the `absolute` positioning is working well. Can revert to a `<table>` if that fails
