### ISSUE TITLE
Setup Grunt build process

### ISSUE THREAD

**Issue by mhulse** [registerguard/drone#4]

**Comment by psullivan6** [comment]
**Suggestion:**
Setup a build process that would allow for several different production versions that are created specifically for each 3rd party.

**Example:**
- an "adicio" directory would have the drone html separated into: head, styles, body, header, and footer
- a legacy directory would have the drone html separated into: header and footer
- etc...

Could achieve this through segmentation of the html as [includes](https://github.com/vanetix/grunt-includes) and then re-build the pieces based on the specific 3rd party

**Comment by psullivan6** [comment]
been done for days :metal:
