### ISSUE TITLE
Sub theme? Really? Readme verbiage. 

### ISSUE THREAD

**Issue by mhulse** [registerguard/drone#5]
Will it ever really be a sub theme?

Won't know until bulldog has bee divided. 

There's some bulldog boiler, but I'm not sure yet if this theme will use any of that (as a git sub module). 

This is not like a "remote" theme. Unmaned theme. Drone theme. :smile: 

The question is, how much default styling should be included?

Should our new sub themes ( like raptor) be built with this 3rd party in mind? In other words, sub themes should have a css file, minus the essentials (layout, base styles, other) that can be plugged in to drone.

**Comment by psullivan6** [comment]
Current setup is all good by my standards. Need more tweaking and/or revisions of thought?

**_2 cents:**_
`bulldog` modularity won't affect the layout styles of `drone`

**Comment by mhulse** [comment]
I think this issue can be closed. I opened it up a while back, but I think we're headed in the right direction now. Closing but feel free to open if I missed something. :+1:
